### ISSUE TITLE
Possible incorrect comment

### ISSUE THREAD

**Issue by SelcukAydi** [GregUtas/robust-services-core#174]
Nodebase::Pooled.h file at line 115:
`  //  Zero for a block that is in use.  Incremented each time through the
   //  audit; if it reaches a threshold, the block is deemed to be orphaned
   //  and is recovered.
   //
   uint8_t orphaned_;`
I guess this comment should say that if orphaned_ is zero then it is in free queue and audited successfully. So if a block is in free queue it means it is not in use, isn't it? If this statement is correct then your comment must be fixed.

**Comment by GregUtas** [comment]
Thank you for mentioning this.
